---
heat_template_version: 2016-04-08

description: Basic infrastructure template cv.4

parameters:
  Cvicenie:
    description: Cisclo cvicenia
    type: string
    default: cv4

  AvailabilityZone:
    description: Availability zone
    type: string
    default: any

  Flavor:
    description: Flavor
    type: string
    default: Linux

  Image:
    description: Image
    type: string
    default: Ubuntu server 14.04 amd64 KIS
    
  Environment:
    description: Environment
    type: string
    default: test
    
  SubnetCidr:
    description: SubnetCidr
    type: string
    default: 10.255.255.0/24

resources:
  Net:
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name: { list_join: [ '-', [ { get_param: 'Environment' }, 'network' ] ] }
      shared: False
      
  Subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: [ '-', [ { get_param: 'Environment' }, 'subnet' ] ] }
      cidr: { get_param: SubnetCidr }
      dns_nameservers:
        - 158.193.152.2
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Net }
   
  Router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: True
      name: { list_join: [ '-', [ { get_param: 'Environment' }, 'router' ] ] }
      external_gateway_infro: {
        enable_snat: True,
        network: ext-net
      }
    
